name: Unit/Integration Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and run Docker tests
        run: |
          docker build -t calibratedcpp-tests .
          docker run --rm calibratedcpp-tests
